// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Domyslny navigator.locks zostaje WLACZONY.
//
// Wczesniej byl tu HOT-FIX podmieniajacy lock na no-op, bo aplikacja zawieszala
// sie na spinnerze. Przyczyna nie byl jednak sam lock, tylko `async` callback
// w onAuthStateChange (src/hooks/useAuth.tsx), ktory wykonywal zapytania do
// bazy trzymajac auth lock - klasyczny deadlock opisany w dokumentacji
// supabase-js. Callback jest juz synchroniczny, wiec blokada nie jest potrzebna.
//
// Wylaczenie locka usuwalo objaw, ale wprowadzalo wyscig przy odswiezaniu
// tokena (rownolegle refresh -> "invalid refresh token" -> wywalona sesja),
// co objawialo sie znikaniem danych po kilku zapytaniach naraz.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    storageKey: 'firezone-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
